---
title: "ENVS-193DS_homework03"
author: "Anna Cote"
date: "2025-05-22"
format:
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
  warning: false # use this to make sure warnings don't show up
repository: https://github.com/annacote2026/ENVS-193DS_homework-03 # link to repository
---

```{r reading-in-packages}
library(tidyverse)
library(here)
library(flextable)
library(janitor)
library(readxl)
library(lubridate)
library(tidyr)
library(dplyr)
library(ggplot2)
```



# 1. Personal Data

a. I could calculate the frequency of each music genre for each given mood association (positive, negative, and neutral) by counting, because I listen to folk music often when I study, so I think the count for times I have listened to folk music while I'm feeling "neutral" (like focused or tired) will be higher than while I'm feeling "negatively".

b. 
```{r cleaning}
personal_data <- read_csv("data/193DS_Personal_Data.csv") |> # starting with my personal data frame
  clean_names()
```

```{r visualizing}
genre_mood_freq <- personal_data |> 
  count(genre, mood_association)
# count occurrences

ggplot(genre_mood_freq,
       aes(x = mood_association,
           y = n,
           fill = genre)) +
  geom_bar(stat = "identity") +
  labs(
    title = "Frequency of Music Genres by Mood Association",
    x = "Mood Association",
    y = "Count",
    fill = "Genre"
  ) + 
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```






